// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqU4NgXDrPYvkOBBFcY_dJJ7QKCMSjCJ8',
    appId: '1:288899170340:web:37cb531b8312592d7158b1',
    messagingSenderId: '288899170340',
    projectId: 'instagram-clone-d0675',
    authDomain: 'instagram-clone-d0675.firebaseapp.com',
    storageBucket: 'instagram-clone-d0675.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ27Md9bPi2L--20JcIJhVR2C_W6uaMhs',
    appId: '1:288899170340:android:a8bae987066db1c67158b1',
    messagingSenderId: '288899170340',
    projectId: 'instagram-clone-d0675',
    storageBucket: 'instagram-clone-d0675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_HO9yOCYtf8PwYqC_NgMboB0LnAL1cLQ',
    appId: '1:288899170340:ios:11dabfcb18e9f2337158b1',
    messagingSenderId: '288899170340',
    projectId: 'instagram-clone-d0675',
    storageBucket: 'instagram-clone-d0675.appspot.com',
    iosClientId: '288899170340-asof3n6cms1eu3ll680tg0okgv0mbj5n.apps.googleusercontent.com',
    iosBundleId: 'com.cooldev.instagramclone',
  );
}
